name: Deploy DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to droplet
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        source: "."
        target: "${{ secrets.DO_USER }}/Agrolink"

    - name: SSH and redeploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /root/Agrolink
          docker stop flask-app || true
          docker rm flask-app || true
          docker build -t flask-app .
          docker run -d --restart always -p 5000:5000 --name flask-app flask-app


